/*
 * Generated by Bluespec Compiler, version 2023.07-7-g527eaa0b (build 527eaa0b)
 * 
 * On Sat Feb 10 22:40:46 UTC 2024
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkAmpelTest.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkAmpelTest::MODEL_mkAmpelTest()
{
  mkAmpelTest_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkAmpelTest()
{
  MODEL_mkAmpelTest *model = new MODEL_mkAmpelTest();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkAmpelTest &INST_top = *((MOD_mkAmpelTest *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_NOT_ampel_testFSM_abort_whas_6_OR_NOT_ampel_te_ETC___d54;
	 tUInt8 DEF_INST_top_DEF_NOT_ampel_testFSM_abort_whas_6_OR_NOT_ampel_te_ETC___d72;
	 tUInt8 DEF_INST_top_DEF_NOT_ampel_testFSM_jj_repeat_count_read__6_BIT_0_7___d70;
	 tUInt8 DEF_INST_top_DEF_NOT_ampel_testFSM_abort_whas_6_OR_NOT_ampel_te_ETC___d40;
	 tUInt8 DEF_INST_top_DEF_ampel_testFSM_abort_whas_AND_ampel_testFSM_abo_ETC___d96;
	 tUInt8 DEF_INST_top_DEF_ampel_testFSM_abort_whas_AND_ampel_testFSM_abo_ETC___d100;
	 tUInt8 DEF_INST_top_DEF_ampel_testFSM_abort_whas_AND_ampel_testFSM_abo_ETC___d6;
	 tUInt8 DEF_INST_top_DEF_NOT_ampel_testFSM_start_wire_whas_OR_NOT_ampel_ETC___d11;
	 tUInt8 DEF_INST_top_DEF_ampel_testFSM_start_wire_whas_AND_ampel_testFS_ETC___d30;
	 tUInt8 DEF_INST_top_DEF_NOT_ampel_testFSM_abort_whas_6_OR_NOT_ampel_te_ETC___d28;
	 tUInt8 DEF_INST_top_DEF_NOT_ampel_testFSM_abort_whas_6_OR_NOT_ampel_te_ETC___d31;
	 tUInt8 DEF_INST_top_DEF_ampel_testFSM_abort_whas_AND_ampel_testFSM_abo_ETC___d34;
	 tUInt8 DEF_INST_top_DEF_NOT_ampel_testFSM_jj_repeat_count_read__6_BIT__ETC___d80;
	 tUInt8 DEF_INST_top_DEF_ampel_testFSM_jj_repeat_count_read__6_BIT_0_7__ETC___d77;
	 tUInt8 DEF_INST_top_DEF_ampel_testFSM_state_mkFSMstate_read__2_EQ_10___d39;
	 tUInt8 DEF_INST_top_DEF_ampel_idle_counter_8_EQ_0___d49;
	 tUInt8 DEF_INST_top_DEF_ampel_testFSM_jj_repeat_count_read__6_BIT_0___d37;
	 tUInt8 DEF_INST_top_DEF_ampel_startetFSM__h34799;
	 tUInt8 DEF_INST_top_DEF_ampel_testFSM_start_reg__h34740;
	 tUInt8 DEF_INST_top_DEF_ampel_testFSM_start_wire_wget____d9;
	 tUInt8 DEF_INST_top_DEF_ampel_testFSM_start_wire_whas____d7;
	 tUInt8 DEF_INST_top_DEF_ampel_testFSM_start_reg_1__h30782;
	 tUInt8 DEF_INST_top_DEF_ampel_testFSM_abort_wget____d5;
	 tUInt8 DEF_INST_top_DEF_ampel_testFSM_abort_whas____d4;
	 tUInt8 DEF_INST_top_DEF_ampel_testFSM_state_fired__h30784;
	 tUInt8 DEF_INST_top_DEF_ampel_testFSM_state_mkFSMstate_read____d32;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_start_reg__dreg_update;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ampel_testFSM_start_reg__dreg_update;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_state_handle_abort;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ampel_testFSM_state_handle_abort;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_state_fired__dreg_update;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ampel_testFSM_state_fired__dreg_update;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_state_every;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ampel_testFSM_state_every;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_restart;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ampel_testFSM_restart;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l27c9;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l33c14;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l36c9;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l41c33;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l52c14;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l53c14;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l54c25;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_r_init_l55c9;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l55c29;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_ovlp_r_update_l55c9;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ampel_testFSM_action_ovlp_r_update_l55c9;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_idle_l25c14;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ampel_testFSM_idle_l25c14;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_fsm_start;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ampel_testFSM_fsm_start;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_startit;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ampel_startit;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_sequel;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ampel_sequel;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_check;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_check;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_5;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_5;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_6;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_6;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_7;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_7;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_8;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_8;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_9;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_9;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_10;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_10;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_11;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_12;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_12;
	 INST_top.DEF_ampel_testFSM_jj_repeat_count_read____d36 = INST_top.INST_ampel_testFSM_jj_repeat_count.METH_read();
	 DEF_INST_top_DEF_ampel_testFSM_state_mkFSMstate_read____d32 = INST_top.INST_ampel_testFSM_state_mkFSMstate.METH_read();
	 DEF_INST_top_DEF_ampel_testFSM_state_fired__h30784 = INST_top.INST_ampel_testFSM_state_fired.METH_read();
	 DEF_INST_top_DEF_ampel_testFSM_abort_wget____d5 = INST_top.INST_ampel_testFSM_abort.METH_wget();
	 DEF_INST_top_DEF_ampel_testFSM_abort_whas____d4 = INST_top.INST_ampel_testFSM_abort.METH_whas();
	 DEF_INST_top_DEF_ampel_testFSM_start_reg_1__h30782 = INST_top.INST_ampel_testFSM_start_reg_1.METH_read();
	 DEF_INST_top_DEF_ampel_testFSM_start_reg__h34740 = INST_top.INST_ampel_testFSM_start_reg.METH_read();
	 DEF_INST_top_DEF_ampel_startetFSM__h34799 = INST_top.INST_ampel_startetFSM.METH_read();
	 DEF_INST_top_DEF_ampel_testFSM_jj_repeat_count_read__6_BIT_0___d37 = (tUInt8)((tUInt8)1u & (INST_top.DEF_ampel_testFSM_jj_repeat_count_read____d36));
	 DEF_INST_top_DEF_ampel_testFSM_state_mkFSMstate_read__2_EQ_10___d39 = DEF_INST_top_DEF_ampel_testFSM_state_mkFSMstate_read____d32 == (tUInt8)10u;
	 DEF_INST_top_DEF_ampel_testFSM_abort_whas_AND_ampel_testFSM_abo_ETC___d6 = DEF_INST_top_DEF_ampel_testFSM_abort_whas____d4 && DEF_INST_top_DEF_ampel_testFSM_abort_wget____d5;
	 DEF_INST_top_DEF_ampel_testFSM_abort_whas_AND_ampel_testFSM_abo_ETC___d34 = DEF_INST_top_DEF_ampel_testFSM_abort_whas_AND_ampel_testFSM_abo_ETC___d6 || DEF_INST_top_DEF_ampel_testFSM_state_mkFSMstate_read____d32 == (tUInt8)0u;
	 DEF_INST_top_DEF_ampel_testFSM_abort_whas_AND_ampel_testFSM_abo_ETC___d96 = (DEF_INST_top_DEF_ampel_testFSM_abort_whas_AND_ampel_testFSM_abo_ETC___d34 || (DEF_INST_top_DEF_ampel_testFSM_jj_repeat_count_read__6_BIT_0___d37 && DEF_INST_top_DEF_ampel_testFSM_state_mkFSMstate_read__2_EQ_10___d39)) && (!DEF_INST_top_DEF_ampel_testFSM_start_reg_1__h30782 || DEF_INST_top_DEF_ampel_testFSM_state_fired__h30784);
	 DEF_INST_top_DEF_ampel_testFSM_abort_whas_AND_ampel_testFSM_abo_ETC___d100 = DEF_INST_top_DEF_ampel_testFSM_abort_whas_AND_ampel_testFSM_abo_ETC___d96 && !DEF_INST_top_DEF_ampel_testFSM_start_reg__h34740;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_sequel = DEF_INST_top_DEF_ampel_testFSM_abort_whas_AND_ampel_testFSM_abo_ETC___d100 && DEF_INST_top_DEF_ampel_startetFSM__h34799;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ampel_sequel = DEF_INST_top_DEF_CAN_FIRE_RL_ampel_sequel;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_startit = DEF_INST_top_DEF_ampel_testFSM_abort_whas_AND_ampel_testFSM_abo_ETC___d100 && !DEF_INST_top_DEF_ampel_startetFSM__h34799;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ampel_startit = DEF_INST_top_DEF_CAN_FIRE_RL_ampel_startit;
	 DEF_INST_top_DEF_NOT_ampel_testFSM_abort_whas_6_OR_NOT_ampel_te_ETC___d28 = !DEF_INST_top_DEF_ampel_testFSM_abort_whas____d4 || !DEF_INST_top_DEF_ampel_testFSM_abort_wget____d5;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l33c14 = DEF_INST_top_DEF_NOT_ampel_testFSM_abort_whas_6_OR_NOT_ampel_te_ETC___d28 && DEF_INST_top_DEF_ampel_testFSM_state_mkFSMstate_read____d32 == (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_ampel_testFSM_action_l33c14 = DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l33c14;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l36c9 = DEF_INST_top_DEF_NOT_ampel_testFSM_abort_whas_6_OR_NOT_ampel_te_ETC___d28 && DEF_INST_top_DEF_ampel_testFSM_state_mkFSMstate_read____d32 == (tUInt8)2u;
	 INST_top.DEF_WILL_FIRE_RL_ampel_testFSM_action_l36c9 = DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l36c9;
	 INST_top.DEF_b__h10619 = INST_top.INST_ampel_idle_counter.METH_read();
	 DEF_INST_top_DEF_ampel_idle_counter_8_EQ_0___d49 = (INST_top.DEF_b__h10619) == (tUInt8)0u;
	 DEF_INST_top_DEF_NOT_ampel_testFSM_abort_whas_6_OR_NOT_ampel_te_ETC___d54 = DEF_INST_top_DEF_NOT_ampel_testFSM_abort_whas_6_OR_NOT_ampel_te_ETC___d28 && (DEF_INST_top_DEF_ampel_testFSM_state_mkFSMstate_read____d32 == (tUInt8)3u || DEF_INST_top_DEF_ampel_testFSM_state_mkFSMstate_read____d32 == (tUInt8)4u);
	 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l52c14 = DEF_INST_top_DEF_ampel_idle_counter_8_EQ_0___d49 && DEF_INST_top_DEF_NOT_ampel_testFSM_abort_whas_6_OR_NOT_ampel_te_ETC___d54;
	 INST_top.DEF_WILL_FIRE_RL_ampel_testFSM_action_l52c14 = DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l52c14;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l53c14 = DEF_INST_top_DEF_NOT_ampel_testFSM_abort_whas_6_OR_NOT_ampel_te_ETC___d28 && DEF_INST_top_DEF_ampel_testFSM_state_mkFSMstate_read____d32 == (tUInt8)5u;
	 INST_top.DEF_WILL_FIRE_RL_ampel_testFSM_action_l53c14 = DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l53c14;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l54c25 = DEF_INST_top_DEF_NOT_ampel_testFSM_abort_whas_6_OR_NOT_ampel_te_ETC___d28 && DEF_INST_top_DEF_ampel_testFSM_state_mkFSMstate_read____d32 == (tUInt8)6u;
	 INST_top.DEF_WILL_FIRE_RL_ampel_testFSM_action_l54c25 = DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l54c25;
	 DEF_INST_top_DEF_NOT_ampel_testFSM_jj_repeat_count_read__6_BIT_0_7___d70 = !DEF_INST_top_DEF_ampel_testFSM_jj_repeat_count_read__6_BIT_0___d37;
	 DEF_INST_top_DEF_NOT_ampel_testFSM_abort_whas_6_OR_NOT_ampel_te_ETC___d72 = DEF_INST_top_DEF_NOT_ampel_testFSM_abort_whas_6_OR_NOT_ampel_te_ETC___d28 && DEF_INST_top_DEF_ampel_testFSM_state_mkFSMstate_read____d32 == (tUInt8)7u;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_r_init_l55c9 = DEF_INST_top_DEF_NOT_ampel_testFSM_jj_repeat_count_read__6_BIT_0_7___d70 && DEF_INST_top_DEF_NOT_ampel_testFSM_abort_whas_6_OR_NOT_ampel_te_ETC___d72;
	 INST_top.DEF_WILL_FIRE_RL_ampel_testFSM_action_r_init_l55c9 = DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_r_init_l55c9;
	 INST_top.DEF_ampel_testFSM_state_can_overlap__h4150 = INST_top.INST_ampel_testFSM_state_can_overlap.METH_read();
	 DEF_INST_top_DEF_NOT_ampel_testFSM_abort_whas_6_OR_NOT_ampel_te_ETC___d40 = DEF_INST_top_DEF_NOT_ampel_testFSM_abort_whas_6_OR_NOT_ampel_te_ETC___d28 && DEF_INST_top_DEF_ampel_testFSM_state_mkFSMstate_read__2_EQ_10___d39;
	 DEF_INST_top_DEF_NOT_ampel_testFSM_jj_repeat_count_read__6_BIT__ETC___d80 = DEF_INST_top_DEF_NOT_ampel_testFSM_jj_repeat_count_read__6_BIT_0_7___d70 && DEF_INST_top_DEF_NOT_ampel_testFSM_abort_whas_6_OR_NOT_ampel_te_ETC___d40;
	 DEF_INST_top_DEF_ampel_testFSM_jj_repeat_count_read__6_BIT_0_7__ETC___d77 = (DEF_INST_top_DEF_ampel_testFSM_jj_repeat_count_read__6_BIT_0___d37 && DEF_INST_top_DEF_NOT_ampel_testFSM_abort_whas_6_OR_NOT_ampel_te_ETC___d72) || (DEF_INST_top_DEF_NOT_ampel_testFSM_abort_whas_6_OR_NOT_ampel_te_ETC___d28 && DEF_INST_top_DEF_ampel_testFSM_state_mkFSMstate_read____d32 == (tUInt8)8u);
	 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_ovlp_r_update_l55c9 = INST_top.DEF_ampel_testFSM_state_can_overlap__h4150 && (DEF_INST_top_DEF_ampel_testFSM_jj_repeat_count_read__6_BIT_0_7__ETC___d77 || DEF_INST_top_DEF_NOT_ampel_testFSM_jj_repeat_count_read__6_BIT__ETC___d80);
	 DEF_INST_top_DEF_WILL_FIRE_RL_ampel_testFSM_action_ovlp_r_update_l55c9 = DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_ovlp_r_update_l55c9;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_fsm_start = DEF_INST_top_DEF_ampel_testFSM_abort_whas_AND_ampel_testFSM_abo_ETC___d96 && DEF_INST_top_DEF_ampel_testFSM_start_reg__h34740;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ampel_testFSM_fsm_start = DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_fsm_start;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_restart = (DEF_INST_top_DEF_ampel_testFSM_start_reg_1__h30782 && !DEF_INST_top_DEF_ampel_testFSM_state_fired__h30784) && DEF_INST_top_DEF_NOT_ampel_testFSM_abort_whas_6_OR_NOT_ampel_te_ETC___d28;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ampel_testFSM_restart = DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_restart;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_start_reg__dreg_update = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ampel_testFSM_start_reg__dreg_update = DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_start_reg__dreg_update;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_state_every = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ampel_testFSM_state_every = DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_state_every;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_state_fired__dreg_update = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ampel_testFSM_state_fired__dreg_update = DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_state_fired__dreg_update;
	 DEF_INST_top_DEF_CAN_FIRE_RL_check = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_check = DEF_INST_top_DEF_CAN_FIRE_RL_check;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l41c33 = !DEF_INST_top_DEF_ampel_idle_counter_8_EQ_0___d49 && DEF_INST_top_DEF_NOT_ampel_testFSM_abort_whas_6_OR_NOT_ampel_te_ETC___d54;
	 INST_top.DEF_WILL_FIRE_RL_ampel_testFSM_action_l41c33 = DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l41c33 && !DEF_INST_top_DEF_WILL_FIRE_RL_check;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_10 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_10 = DEF_INST_top_DEF_CAN_FIRE___me_check_10;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_11 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_11 = DEF_INST_top_DEF_CAN_FIRE___me_check_11;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_12 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_12 = DEF_INST_top_DEF_CAN_FIRE___me_check_12;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_5 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_5 = DEF_INST_top_DEF_CAN_FIRE___me_check_5;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_6 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_6 = DEF_INST_top_DEF_CAN_FIRE___me_check_6;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_7 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_7 = DEF_INST_top_DEF_CAN_FIRE___me_check_7;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_9 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_9 = DEF_INST_top_DEF_CAN_FIRE___me_check_9;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_8 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_8 = DEF_INST_top_DEF_CAN_FIRE___me_check_8;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ampel_sequel)
	   INST_top.RL_ampel_sequel();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ampel_startit)
	   INST_top.RL_ampel_startit();
	 if (INST_top.DEF_WILL_FIRE_RL_ampel_testFSM_action_l33c14)
	   INST_top.RL_ampel_testFSM_action_l33c14();
	 if (INST_top.DEF_WILL_FIRE_RL_ampel_testFSM_action_l36c9)
	   INST_top.RL_ampel_testFSM_action_l36c9();
	 if (INST_top.DEF_WILL_FIRE_RL_ampel_testFSM_action_l52c14)
	   INST_top.RL_ampel_testFSM_action_l52c14();
	 if (INST_top.DEF_WILL_FIRE_RL_ampel_testFSM_action_l41c33)
	   INST_top.RL_ampel_testFSM_action_l41c33();
	 if (INST_top.DEF_WILL_FIRE_RL_ampel_testFSM_action_l53c14)
	   INST_top.RL_ampel_testFSM_action_l53c14();
	 if (INST_top.DEF_WILL_FIRE_RL_ampel_testFSM_action_l54c25)
	   INST_top.RL_ampel_testFSM_action_l54c25();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ampel_testFSM_action_ovlp_r_update_l55c9)
	   INST_top.RL_ampel_testFSM_action_ovlp_r_update_l55c9();
	 if (INST_top.DEF_WILL_FIRE_RL_ampel_testFSM_action_r_init_l55c9)
	   INST_top.RL_ampel_testFSM_action_r_init_l55c9();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ampel_testFSM_fsm_start)
	   INST_top.RL_ampel_testFSM_fsm_start();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ampel_testFSM_restart)
	   INST_top.RL_ampel_testFSM_restart();
	 DEF_INST_top_DEF_ampel_testFSM_start_wire_whas____d7 = INST_top.INST_ampel_testFSM_start_wire.METH_whas();
	 DEF_INST_top_DEF_ampel_testFSM_start_wire_wget____d9 = INST_top.INST_ampel_testFSM_start_wire.METH_wget();
	 DEF_INST_top_DEF_ampel_testFSM_start_wire_whas_AND_ampel_testFS_ETC___d30 = DEF_INST_top_DEF_ampel_testFSM_start_wire_whas____d7 && DEF_INST_top_DEF_ampel_testFSM_start_wire_wget____d9;
	 DEF_INST_top_DEF_NOT_ampel_testFSM_abort_whas_6_OR_NOT_ampel_te_ETC___d31 = DEF_INST_top_DEF_NOT_ampel_testFSM_abort_whas_6_OR_NOT_ampel_te_ETC___d28 || DEF_INST_top_DEF_ampel_testFSM_start_wire_whas_AND_ampel_testFS_ETC___d30;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l27c9 = (DEF_INST_top_DEF_NOT_ampel_testFSM_abort_whas_6_OR_NOT_ampel_te_ETC___d31 && ((DEF_INST_top_DEF_ampel_testFSM_start_wire_whas_AND_ampel_testFS_ETC___d30 && DEF_INST_top_DEF_ampel_testFSM_abort_whas_AND_ampel_testFSM_abo_ETC___d34) || ((DEF_INST_top_DEF_ampel_testFSM_jj_repeat_count_read__6_BIT_0___d37 && DEF_INST_top_DEF_ampel_testFSM_start_wire_whas_AND_ampel_testFS_ETC___d30) && DEF_INST_top_DEF_NOT_ampel_testFSM_abort_whas_6_OR_NOT_ampel_te_ETC___d40))) && !(((DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_ovlp_r_update_l55c9 || DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_r_init_l55c9) || (DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l54c25 || DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l53c14)) || ((DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l52c14 || DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l41c33) || (DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l36c9 || DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l33c14)));
	 INST_top.DEF_WILL_FIRE_RL_ampel_testFSM_action_l27c9 = DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l27c9;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l55c29 = (DEF_INST_top_DEF_NOT_ampel_testFSM_abort_whas_6_OR_NOT_ampel_te_ETC___d31 && (DEF_INST_top_DEF_ampel_testFSM_jj_repeat_count_read__6_BIT_0_7__ETC___d77 || ((DEF_INST_top_DEF_NOT_ampel_testFSM_abort_whas_6_OR_NOT_ampel_te_ETC___d28 && DEF_INST_top_DEF_ampel_testFSM_state_mkFSMstate_read____d32 == (tUInt8)9u) || DEF_INST_top_DEF_NOT_ampel_testFSM_jj_repeat_count_read__6_BIT__ETC___d80))) && !((((DEF_INST_top_DEF_CAN_FIRE_RL_ampel_sequel || DEF_INST_top_DEF_CAN_FIRE_RL_ampel_startit) || (DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_fsm_start || DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_r_init_l55c9)) || ((DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l54c25 || DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l53c14) || (DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l52c14 || DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l41c33))) || (DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l36c9 || DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l33c14));
	 INST_top.DEF_WILL_FIRE_RL_ampel_testFSM_action_l55c29 = DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l55c29;
	 DEF_INST_top_DEF_NOT_ampel_testFSM_start_wire_whas_OR_NOT_ampel_ETC___d11 = !DEF_INST_top_DEF_ampel_testFSM_start_wire_whas____d7 || !DEF_INST_top_DEF_ampel_testFSM_start_wire_wget____d9;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_idle_l25c14 = ((DEF_INST_top_DEF_ampel_testFSM_jj_repeat_count_read__6_BIT_0___d37 && DEF_INST_top_DEF_NOT_ampel_testFSM_start_wire_whas_OR_NOT_ampel_ETC___d11) && DEF_INST_top_DEF_NOT_ampel_testFSM_abort_whas_6_OR_NOT_ampel_te_ETC___d40) && !(((DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_ovlp_r_update_l55c9 || DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_r_init_l55c9) || (DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l54c25 || DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l53c14)) || ((DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l52c14 || DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l41c33) || (DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l36c9 || DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l33c14)));
	 DEF_INST_top_DEF_WILL_FIRE_RL_ampel_testFSM_idle_l25c14 = DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_idle_l25c14;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_state_handle_abort = (DEF_INST_top_DEF_ampel_testFSM_abort_whas_AND_ampel_testFSM_abo_ETC___d6 && DEF_INST_top_DEF_NOT_ampel_testFSM_start_wire_whas_OR_NOT_ampel_ETC___d11) && !((((DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_ovlp_r_update_l55c9 || DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_r_init_l55c9) || (DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l54c25 || DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l53c14)) || ((DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l52c14 || DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l41c33) || (DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l36c9 || DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_action_l33c14))) || DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_restart);
	 DEF_INST_top_DEF_WILL_FIRE_RL_ampel_testFSM_state_handle_abort = DEF_INST_top_DEF_CAN_FIRE_RL_ampel_testFSM_state_handle_abort;
	 if (INST_top.DEF_WILL_FIRE_RL_ampel_testFSM_action_l27c9)
	   INST_top.RL_ampel_testFSM_action_l27c9();
	 if (INST_top.DEF_WILL_FIRE_RL_ampel_testFSM_action_l55c29)
	   INST_top.RL_ampel_testFSM_action_l55c29();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ampel_testFSM_start_reg__dreg_update)
	   INST_top.RL_ampel_testFSM_start_reg__dreg_update();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ampel_testFSM_state_handle_abort)
	   INST_top.RL_ampel_testFSM_state_handle_abort();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_check)
	   INST_top.RL_check();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_5)
	   INST_top.__me_check_5();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_6)
	   INST_top.__me_check_6();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_7)
	   INST_top.__me_check_7();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_8)
	   INST_top.__me_check_8();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_9)
	   INST_top.__me_check_9();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_10)
	   INST_top.__me_check_10();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_11)
	   INST_top.__me_check_11();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_12)
	   INST_top.__me_check_12();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ampel_testFSM_idle_l25c14)
	   INST_top.RL_ampel_testFSM_idle_l25c14();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ampel_testFSM_state_every)
	   INST_top.RL_ampel_testFSM_state_every();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ampel_testFSM_state_fired__dreg_update)
	   INST_top.RL_ampel_testFSM_state_fired__dreg_update();
	 INST_top.INST_ampel_testFSM_state_fired_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ampel_testFSM_state_overlap_pw.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ampel_testFSM_state_set_pw.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ampel_testFSM_abort.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ampel_testFSM_start_reg_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ampel_testFSM_start_wire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ampel_pedestrian_request.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ampel_pedestrian_state.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ampel_state.clk((tUInt8)1u, (tUInt8)1u);
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_ampel_state.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_ampel_pedestrian_state.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_ampel_pedestrian_request.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_ampel_startetFSM.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_ampel_handeldRequest.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_ampel_testFSM_start_reg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_ampel_testFSM_start_reg_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_ampel_testFSM_jj_repeat_count.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_ampel_testFSM_state_mkFSMstate.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_ampel_testFSM_state_fired.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_ampel_testFSM_state_can_overlap.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_counter.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkAmpelTest::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkAmpelTest_instance = new MOD_mkAmpelTest(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkAmpelTest_instance->INST_ampel_state.set_clk_0)("CLK");
  (mkAmpelTest_instance->INST_ampel_pedestrian_state.set_clk_0)("CLK");
  (mkAmpelTest_instance->INST_ampel_pedestrian_request.set_clk_0)("CLK");
  (mkAmpelTest_instance->INST_ampel_testFSM_start_wire.set_clk_0)("CLK");
  (mkAmpelTest_instance->INST_ampel_testFSM_start_reg_2.set_clk_0)("CLK");
  (mkAmpelTest_instance->INST_ampel_testFSM_abort.set_clk_0)("CLK");
  (mkAmpelTest_instance->INST_ampel_testFSM_state_set_pw.set_clk_0)("CLK");
  (mkAmpelTest_instance->INST_ampel_testFSM_state_overlap_pw.set_clk_0)("CLK");
  (mkAmpelTest_instance->INST_ampel_testFSM_state_fired_1.set_clk_0)("CLK");
  (mkAmpelTest_instance->set_clk_0)("CLK");
}
void MODEL_mkAmpelTest::destroy_model()
{
  delete mkAmpelTest_instance;
  mkAmpelTest_instance = NULL;
}
void MODEL_mkAmpelTest::reset_model(bool asserted)
{
  (mkAmpelTest_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkAmpelTest::get_instance()
{
  return mkAmpelTest_instance;
}

/* Fill in version numbers */
void MODEL_mkAmpelTest::get_version(char const **name, char const **build)
{
  *name = "2023.07-7-g527eaa0b";
  *build = "527eaa0b";
}

/* Get the model creation time */
time_t MODEL_mkAmpelTest::get_creation_time()
{
  
  /* Sat Feb 10 22:40:46 UTC 2024 */
  return 1707604846llu;
}

/* State dumping function */
void MODEL_mkAmpelTest::dump_state()
{
  (mkAmpelTest_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkAmpelTest & mkAmpelTest_backing(tSimStateHdl simHdl)
{
  static MOD_mkAmpelTest *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkAmpelTest(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkAmpelTest::dump_VCD_defs()
{
  (mkAmpelTest_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkAmpelTest::dump_VCD(tVCDDumpType dt)
{
  (mkAmpelTest_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkAmpelTest_backing(sim_hdl));
}
